name: Up

# on: [push]

# recommended
on:
  schedule:
    - cron: '5 5 * * *'
  push:


jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
    
      - name: 'Get Weather'
        run: 
          bash ./weather.sh
        env:       
          
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
